services:
  db:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: acobuccio
      MYSQL_USER: acobuccio
      MYSQL_PASSWORD: acobuccio
    networks:
      - default
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
      UPLOAD_LIMIT: 300M
    networks:
      - default
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - default
  back:
    depends_on:
      - db
    build: ./back
    image: acobuccio_back
    container_name: acobuccio_back
    ports:
      - '8000:8000'
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: acobuccio
      DB_USERNAME: acobuccio
      DB_PASSWORD: acobuccio
    networks:
      - default
  front:
    depends_on:
      - back
    build: ./front
    image: acobuccio_front
    container_name: acobuccio_front
    ports:
      - '3000:3000'
    restart: always
    environment:
      API_BASE: http://localhost:8000/api
      AUTH_COOKIES_EXPIRATION: 20
    networks:
      - default
networks:
  default:
volumes:
  db_data: