version: '3'

services:
  db:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: acobuccio
      MYSQL_USER: acobuccio
      MYSQL_PASSWORD: acobuccio
    networks:
      - default
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
      UPLOAD_LIMIT: 300M
    networks:
      - default
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - default
  front:
    build: ./front
    ports:
      - '3000:3000'
    restart: always
    volumes: ['./front:/var/www/html']
    networks:
      - default
  back:
    depends_on:
      - db
    build: ./back
    ports:
      - '8000:8000'
    restart: always
    volumes: ['./back:/var/www/html']
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: acobuccio
      DB_USERNAME: acobuccio
      DB_PASSWORD: acobuccio
    networks:
      - default
networks:
  default:
volumes:
  db_data: